### ISSUE TITLE
Couldn't install the local version of the Archway Docs

### ISSUE THREAD

**Issue by lomarketing** [archway-network/archway-docs#60]
Trying to install the Archway Docs on Macbook Pro M1  
macOS Monterey ver 12.3.1
<img width="569" alt="image" src="https://user-images.githubusercontent.com/38462485/161544727-db4208a7-5b62-450f-a506-9d5ed04341ad.png">

1. Installed the Node.js for Mac M1 ver 17.8.0 
<img width="498" alt="image" src="https://user-images.githubusercontent.com/38462485/161545379-09c987a2-d2fc-4b2c-b75a-415de1f02cd1.png">

2. Installed the npm ver 8.5.5
<img width="462" alt="image" src="https://user-images.githubusercontent.com/38462485/161545524-6a68d24d-c311-4984-9d2e-f8419f3ad674.png">

3. Git clone https://github.com/archway-network/archway-docs.git
4. Then do npm install from the directory /archway-docs
5. npm start
6. And have such errors after a few screens

![telegram-cloud-photo-size-2-5357056736743242094-y](https://user-images.githubusercontent.com/38462485/161546447-4e53dd9b-dd9b-4e18-83e6-b24f6aaf703f.jpg)
 then
![telegram-cloud-photo-size-2-5357056736743242095-y](https://user-images.githubusercontent.com/38462485/161546516-938d0d7b-9f91-4db3-ad77-64b91852fa49.jpg)
![telegram-cloud-photo-size-2-5357056736743242096-y](https://user-images.githubusercontent.com/38462485/161546638-db513a0f-a804-44f0-9645-af2aeb8d2e2f.jpg)
![telegram-cloud-photo-size-2-5357056736743242097-y](https://user-images.githubusercontent.com/38462485/161546684-6b150a92-e88d-405b-b14a-1a57a4a1cf69.jpg)

**Comment by drewstaylor** [comment]
You need to use node 14.x for Docusaurus 2. Also, be aware that node and npm are installed per user and the root user may have a different node versions, but there shouldn't be any reason you'd need to use `sudo` for running this web app

**Comment by drewstaylor** [comment]
@lomarketing thanks for flagging this. I updated https://docs.archway.io/docs/participate/contribute/#preview-draft-prs-on-a-local-web-browser with a tip explaining the dependency requirements
