### ISSUE TITLE
Cargo.toml and project versioning explainer

### ISSUE THREAD

**Issue by santanaluiz** [archway-network/archway-docs#69]
## Description

[Description to be reviewed]
We need to create an explainer for our `Cargo.toml` file and project versioning

## TODO
- [x] Set metadata is missing from the docs at the moment
- [ ] Document Bridge to CosmWasm documentation

**Comment by santanaluiz** [comment]
@drewstaylor can you update us on the status of this ticket?

**Comment by drewstaylor** [comment]
@santanaluiz working on it today
