### ISSUE TITLE
Translation of documentation into Spanish and Russian

### ISSUE THREAD

**Issue by VArt03** [archway-network/archway-docs#79]
https://medium.com/@vartoff03/sobre-archway-es-4638f403f8b3

**Comment by VArt03** [comment]
https://medium.com/@vartoff03/об-archway-ru-f2fdb222eb33

Translation of documentation for Russian-speaking comrades.

**Comment by drewstaylor** [comment]
Feel free to add this as a [Pull Request](https://docs.github.com/en/pull-requests). It's not really an issue so I am closing this.
