### ISSUE TITLE
Add a search functionality for the docs website

### ISSUE THREAD

**Issue by santanaluiz** [archway-network/archway-docs#81]
## Description

We need to add search functionality to our docs website, as today it can get a bit tricky to find information, leading to more questions than needed in our discord as well.

## Design
https://www.figma.com/file/MB2oT7gPFWRGliFspaGsrh/?node-id=1700%3A16661

@ Rick's message on this item:

> You’ll find the search bar in the top navigation in this design.
> I think it would be nice to use Algolia. It works with cmd+K (and the equivalent on windows)
> Please see https://docs.solana.com/ as an example.
> Let’s make sure we use the color theme of Archway for the extended search UI that will open when you interact with the search functionality.
> Let me know if there are any Qs or additional designs needed.

## TODO

- [x] Create design (Rick)
- [x] Add search functionality

**Comment by drewstaylor** [comment]
I've applied to the Algolia DocsSearch program as per Docusaurus recommendations. Since Algolia is officially supported by Docusaurus.

As long as my application is approved the integration will be quick and easy, but it could take up to a week for approval to go through

**Comment by drewstaylor** [comment]
This feature is ready to review and may require additional CSS touch ups. Otherwise, the functionality is working nicely.
