### ISSUE TITLE
Docs site not updating after pushes to main

### ISSUE THREAD

**Issue by drewstaylor** [archway-network/archway-docs#85]
@helder-moreira Can you look into the deploy configuration? I saw your CI commit from 10 days ago re-naming some of the settings. 

Right now the site isn't deploying new changes, but the CI routines did finish:
https://github.com/archway-network/archway-docs/runs/6919084038?check_suite_focus=true

**Comment by drewstaylor** [comment]
I'm wondering if this could be why:

```
Run FirebaseExtended/action-hosting-deploy@v0
Verifying firebase.json exists
Setting up CLI credentials
Deploying to production site
***
  details_url: 'https://archway-network.web.app/',
  conclusion: 'success',
  output: ***
    title: 'Production deploy succeeded',
    summary: '[archway-network.web.app](https://archway-network.web.app/)'
  ***
***
```

https://archway-network.web.app/ seems to be the landing website (not the docs site)

**Comment by drewstaylor** [comment]
Update: Firebase deployment is working and the site not updating seems to be a DNS issue

Page was updated correctly [here](https://docs-archway.web.app/docs/create/getting-started/install/#install-archwayd-using-docker)

But docs website is showing the legacy version [here](https://docs-archway.web.app/docs/create/getting-started/install/#install-archwayd-using-docker)

@shahbazn is investigating 👌

**Comment by helder-moreira** [comment]
Firebase deployments were migrated but the domains were not. So the only thing that is required is to add the correct domain to the new firebase project.

**Comment by drewstaylor** [comment]
Fixed
